In [1]:
import pandas as pd

df = pd.read_csv("messy_data.csv")
df

,Customer_ID,Name,Age,Gender,City,Salary,Join_Date
0,1,Amit Sharma,25,Male,Mumbai,50000,2022-01-15
1,2,Priya Singh,NaN,Female,Delhi,60000,2022-02-20
2,3,Rahul Verma,30,Male,Delhi,NaN,2022-03-10
3,4,Neha Gupta,28,Female,Mumbai,52000,2022/04/05
4,5,Arjun Patel,35,Male,NaN,70000,2022-05-12
5,6,Kavya Nair,27,Female,Bangalore,not_available,2022-06-18
6,7,Rohit Mehta,29,Male,Mumbai,58000,2022-07-22
7,8,Sneha Reddy,abc,Female,Hyderabad,62000,2022-08-30
8,9,Vikas Jain,31,Male,Delhi,61000,NaN
9,10,Anjali Desai,26,Female,Mumbai,55000,2022-10-05
10,10,Anjali Desai,26,Female,Mumbai,55000,2022-10-05
11,11,Karan Malhotra,40,Male,Delhi,80000,2022-11-11
12,12,Pooja Shah,29,Female,Bangalore,72000,2022-12-01

In [2]:
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  13 non-null     int64
 1   Name         13 non-null     str
 2   Age          12 non-null     str
 3   Gender       13 non-null     str
 4   City         12 non-null     str
 5   Salary       12 non-null     str
 6   Join_Date    12 non-null     str
dtypes: int64(1), str(6)
memory usage: 860.0 bytes

np.int64(1)

In [3]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [4]:
df["Age"]= pd.to_numeric(df["Age"],errors="coerce")

In [5]:
df["Age"].fillna(df["Age"].mean(), inplace=True)

C:\Users\ashmi\AppData\Local\Temp\ipykernel_19152\1809399462.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].mean(), inplace=True)

0     25.0
1     30.0
2     30.0
3     28.0
4     35.0
5     27.0
6     29.0
7     30.0
8     31.0
9     26.0
11    40.0
12    29.0
Name: Age, dtype: float64

In [6]:
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

In [7]:
df["Salary"].fillna(df["Salary"].median(), inplace=True)

C:\Users\ashmi\AppData\Local\Temp\ipykernel_19152\2465791117.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Salary"].fillna(df["Salary"].median(), inplace=True)

0     50000.0
1     60000.0
2     60500.0
3     52000.0
4     70000.0
5     60500.0
6     58000.0
7     62000.0
8     61000.0
9     55000.0
11    80000.0
12    72000.0
Name: Salary, dtype: float64

In [8]:
df["City"].fillna("Unknown", inplace=True)

C:\Users\ashmi\AppData\Local\Temp\ipykernel_19152\4032887332.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["City"].fillna("Unknown", inplace=True)

0        Mumbai
1         Delhi
2         Delhi
3        Mumbai
4       Unknown
5     Bangalore
6        Mumbai
7     Hyderabad
8         Delhi
9        Mumbai
11        Delhi
12    Bangalore
Name: City, dtype: str

In [9]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

In [12]:
df["Join_Date"] = df["Join_Date"].ffill()

In [15]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
Index: 12 entries, 0 to 12
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  12 non-null     int64
 1   Name         12 non-null     str
 2   Age          10 non-null     float64
 3   Gender       12 non-null     str
 4   City         11 non-null     str
 5   Salary       10 non-null     float64
 6   Join_Date    12 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 768.0 bytes

Customer_ID    0
Name           0
Age            2
Gender         0
City           1
Salary         2
Join_Date      0
dtype: int64

## 🧹 Data Cleaning Summary

- Removed duplicate records  
- Converted Age and Salary to numeric  
- Handled missing values using mean/median  
- Standardized date format  
- Filled missing categorical values

In [24]:
df.head()

   Customer_ID         Name   Age  Gender     City   Salary  Join_Date
0            1  Amit Sharma  25.0    Male   Mumbai  50000.0 2022-01-15
1            2  Priya Singh  30.0  Female    Delhi  60000.0 2022-02-20
2            3  Rahul Verma  30.0    Male    Delhi  60500.0 2022-03-10
3            4   Neha Gupta  28.0  Female   Mumbai  52000.0 2022-03-10
4            5  Arjun Patel  35.0    Male  Unknown  70000.0 2022-05-12